baseURL = 'novembersecond.net'
languageCode = 'en-us'
title = 'November Second'
[params]
subtitle = 'Software Solutions'
description = 'Software Solutions'
og_image = "/icon.png"
customcss = ["css/custom.css"]
